typename struct lis
{
    datetype Sno[max];
    char name[max][20];
    char class[max][20];
    datetype sex[max];
    int last;
}lis,*list;
list La;
la = (list)malloc(sizeof(lis));
/***************************
 * for(int i= ...)
 * la.sno[i] = ....
 * la,name[i] = ...
 * la.class[i] = ..
 * ....
 * ....
 * ....
 * **************************/
void InserList(list* la, int x){
    sno[i] == x
    then i = last;
    sno[k] = sno[k - 1];
    k++;
    ...
    class[] ...
    name [] ...
    sex  [] ...
    ...
}